services:
  contact-site:
    build: .
    network_mode: host
    env_file:
      - .env
    environment:
      PORT: "3021"
      HOST: "0.0.0.0"
      BODY_SIZE_LIMIT: "12M"
    restart: unless-stopped
